spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:crudh2 # h2 database 連接位址
    driver-class-name: org.h2.Driver # 配置driver
    username: rigby
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect